### PR TITLE
Chore: update react-docgen

### PR DESCRIPTION
**Pull request by smashercosmo**
closes https://github.com/styleguidist/react-styleguidist/issues/1279
(reference: https://babeljs.io/docs/en/options#filename)

### CODE REVIEW

**Comment by smashercosmo** [comment]
I'm not quite sure, if it's a breaking change or not) But I have a feeling that it is, because it's affects how babel config is resolved.

**Comment by danez** [comment]
I also just released 4.0.1 with a fix for proptypes support (https://github.com/reactjs/react-docgen/pull/330).

**Comment by smashercosmo** [comment]
Ok, I'll update

**Comment by smashercosmo** [comment]
react-docgen updated to 4.0.1

**Comment by smashercosmo** [comment]
react-docgen updated to 4.1.0

**Comment by sapegin** [comment]
We're going to merge this for now. If it breaks the whole internet, @okonet offered to fix it ;-)

**Pull request merged**
