### PR TITLE
Fixes for main prop and Node API exception handling

### PR DESCRIPTION
**Pull request by arizonatribe**
Fixed main prop (in package.json) and Node API exception handling (for StyleguidistError instances)

#1292 
#1291

### CODE REVIEW

**Comment by sapegin** [comment]
Please revert version number changes and I'll merge it — looks good otherwise.

**Comment by arizonatribe** [comment]
Okay should be all set now

**Comment by sapegin** [comment]
Could you please test that this code still shows a correct link with an anchor?

https://github.com/styleguidist/react-styleguidist/blob/2bea3d6bd14a06d85ee590d9e08206e2e2f973cf/src/bin/styleguidist.js#L51-L57

**Comment by arizonatribe** [comment]
All your tests passed; what do you mean?

**Comment by arizonatribe** [comment]
I just went through all the source code and I can't even find anywhere where you _are_ passing a link/anchor into a new `StyleguidistError`.

**Comment by arizonatribe** [comment]
Are you trying to indicate that when you're creating a new `StyleguidistError` from another one (in the `scripts/config.js`) that the `.extra` from the original error is supposed to map to the `.anchor` on the new error?

If that's the case, that seems a bit hacky and brittle. This would make more sense:
```js
if (exception instanceof StyleguidistError) {
  throw new StyleguidistError(
    'Something is wrong with your style guide config',
    exception.toString(),
    exception.anchor
  );
}
```

**Comment by sapegin** [comment]
I think I was able fo fix both issues 🤔

**Comment by arizonatribe** [comment]
You asked about the anchor/link, but the fix you did on your own doesn't pass that through to the constructor of the next error. Does that make sense?

**Pull request closed without merging**
