### PR TITLE
Update mini-html-webpack-plugin to 2.0.0 (milestone 10.0.0?)

### PR DESCRIPTION
**Pull request by J-Kallunki**
Updates `mini-html-webpack-plugin` to 2.0.0 and `@vxna/mini-html-webpack-template` to 1.0.0.
Breaking changes in 2.0.0 don't affect `@vxna/mini-html-webpack-template@1.0.0`. Tests passes.

Should this be included in the milestone 10.0.0 (https://github.com/styleguidist/react-styleguidist/milestone/17) as said earlier here: https://github.com/styleguidist/react-styleguidist/issues/1363#issuecomment-493339738

### CODE REVIEW

**Comment by J-Kallunki** [comment]
This is required to be able to create accessible styleguide: https://github.com/styleguidist/mini-html-webpack-plugin/pull/8

**Comment by sapegin** [comment]
Cool, thanks!

**Comment by sapegin** [comment]
Oops, why did it close it? 🤔

**Comment by russell-ingram** [comment]
How does this work? I've updated to 10.1 and made sure the mini-html-webpack-plugin is 2.0.0 and yet no matter what I try, I can't get the lang html attribute to show up.

**Comment by russell-ingram** [comment]
@sapegin @J-Kallunki Why was the comment above marked as off topic when it relates to accessibility which is specifically what 2.0.0 was brought in for? Even more specifically, the mini-html-webpack-plugin update was in part started because of the lang attribute not appearing: https://github.com/styleguidist/mini-html-webpack-plugin/pull/8. This appears to work in the mini-html-webpack-plugin itself, but I can't seem to get it to work in react-styleguidist. This doesn't appear to do what it was intended to do. Where should I bring this up if not here?

**Comment by sapegin** [comment]
> Why was the comment above marked as off topic

Primarily because of the tone of your messages. Please be more mindful when you write: this is an open source project.

This feature was never implemented in Styleguidist, and this PR is only a prerequisite to do it. Feel free to send a pull request though.

**Comment by russell-ingram** [comment]
@sapegin I literally just asked "How does this work? I can't figure it out" Maybe there is some language barrier here, but that is about as tone-free as a question can get. I would argue that marking the question as irrelevant and ignoring it is MUCH more rude, but then we'd truly be getting into "off-topic" discussion.

I thank you for your work on this project and thank you for answering my question. I will look into making an update an opening a PR for the issue.

**Comment by J-Kallunki** [comment]
It works with `styleguide.config.js`:
```
module.exports = {
  template: {
    lang: 'en'
  }
}
```

**Pull request merged**
