### PR TITLE
Updated jss-isolate

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by sapegin** [comment]
Does it fix #739?

**Comment by Andarist** [comment]
Yeah :)

**Comment by sapegin** [comment]
Cool, thanks!

**Comment by gscottolson** [comment]
@sagepin: Do you have an estimated publish date for v 6.2.0? This Safari font color bug is really impacting the correctness of my style guide. 😄

**Comment by Andarist** [comment]
@gscottolson you can use [this workaround](https://github.com/styleguidist/react-styleguidist/issues/764#issuecomment-357543200) in the meantime

**Comment by gscottolson** [comment]
@ Andarist I must have missed this. Thanks for pointing it out. 🍻

**Pull request merged**
