### PR TITLE
Add support for ie9+ (For Preview)

### PR DESCRIPTION
**Pull request by viktop**
- Added support for IE9+
- Added missing EventSource `eventsource-polyfill`

### CODE REVIEW

**Comment by sapegin** [comment]
We can’t use babel-standalone (we did that before) because it’s huge. Support for IE9 doesn’t worth such increase in bundle size anyway.

But there’s a plan to make transpiler customizable via config.

/cc @n1313

**Comment by viktop** [comment]
@sapegin What about detecting IE10 and less ?
`if (navigator.userAgent.indexOf("MSIE") >= 0)` // Use babel in this case

**Comment by viktop** [comment]
@sapegin So what's wrong with https://github.com/n1313/react-styleguidist/commit/e697099f6af87dcbb9794d06efaf01699207961e  ?

**Comment by sapegin** [comment]
It implements a different feature: a Buble/Babel switch. We need just a config option to specify custom transpilation function that will run Buble by default.

**Comment by viktop** [comment]
@sapegin That's something we actually need. When can we have this merged? Any idea? Thanks

**Comment by sapegin** [comment]
If @n1313 is working on that it‘s better to ask him. Otherwise you can send a pull request to the `next` branch (it’s quite simple to implement there and more complicated in master). (It’s a beta of the next major release, see #223 for details.)

**Comment by viktop** [comment]
@sapegin Thanks!

**Comment by viktop** [comment]
@sapegin next branch doesn't even run in IE11 and any IE... 
screen shot 2017-01-14 at 10 33 15 pm
It's a step back for us.

**Comment by sapegin** [comment]
> It's a step back for us.

This kind of comments are very uproductive. If you want to help us please do, if you want to complain go somewhere else.

**Comment by viktop** [comment]
We want to progress not to regress.

bro-do-you-even-test-thumb

**Pull request closed without merging**
