### PR TITLE
fix devServer crash

### LINKED ISSUE #1714: Dev Server crash when upgrade to 11.1.2
**Current behavior**

run script `styleguidist server`, after reload page, the dev server is crash

**To reproduce**
1.upgrade to 11.1.2 or 11.1.1, run styleguidist server and open styleguidist in chrome
2.Open chrome console panel
3. type `new WebSocket('ws://localhost:6060/sockjs-node')` and press enter
4. repeat step3 twice 
5. server crash

I found the reason: 
https://github.com/styleguidist/react-styleguidist/issues/1705#issuecomment-726536041

I think this should be config in https://github.com/styleguidist/react-styleguidist/blob/master/src/scripts/create-server.ts#L12, no in user webpack.config.js

**Expected behavior**
server don't crash

### PR DESCRIPTION
**Pull request by malcolm-kee**
resolves #1714 #1705 

- Fix based on advice from @lyz810
- Tested locally the issue is fixed (able to reproduce the bug by reverting the fix)

### CODE REVIEW

**Comment by malcolm-kee** [comment]
@sapegin would you mind to take a look?

**Comment by sapegin** [comment]
Thanks!

**Comment by sapegin** [comment]
Looks like it's breaking the props table, we shouldn't use this large font there:

image

**Comment by sapegin** [comment]
Looks like it's now printing a warning on start but the dev server isn't crashing anymore.

```
⚠ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
```

**Pull request merged**
