### PR TITLE
Fix: repair user alias rsg-components when provided

### PR DESCRIPTION
**Pull request by kopax**
Current code doesn't permit to alias `rsg-components`.

Only way of doing it is using `config.styleguideComponents`.

This allow user to set an alias.

### CODE REVIEW

**Comment by kopax** [comment]
Can we include this in futur release?

**Comment by sapegin** [comment]
What problem you're trying to solve? It's not supposed to be changed via `webpackConfig` because it may break Styleguidist. You could change it with `dangerouslyUpdateWebpackConfig`.

**Comment by kopax** [comment]
Fw https://github.com/styleguidist/react-styleguidist/issues/984 @sapegin we have hit this while trying to use the alias. I wonder why we should keep such a restriction, the `:fix` could be accepted as a `:feature` if not forbidden. Otherwise, this should be clearly stated in the documentation as a restriaction. 

> It's not supposed to be changed via `webpackConfig` because it may break Styleguidist. 

Could you elaborate or give user case where it break styleguidist?

> You could change it with `dangerouslyUpdateWebpackConfig`.

Thanks, I am not reading method starting with `dangerously` but now I did read it : https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md#dangerouslyupdatewebpackconfig

I'd like if possible to know when it can break the react-styleguidist.

**Comment by sapegin** [comment]
I still don't see what problem you're trying to solve, that can't be solved with `styleguideComponents` or `dangerouslyUpdateWebpackConfig` optons. Any changes to webpack config required by Styleguidist itself are potentially dangerous and not allowed.

**Pull request closed without merging**
