### PR TITLE
fix: change state assigment

### PR DESCRIPTION
**Pull request by nicoffee**
Must solve #864.

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks! Would be awesome if you can add some tests for this part of the code.

**Comment by nicoffee** [comment]
Okay, will do.

**Comment by nicoffee** [comment]
@sapegin, i need some help testing this case.
Should i export PreviewComponent from `Preview.js` in order to test his `setInitialState()` method directly, or should i somehow test it through `Preview` component, and if so, how exactly?
For now, i did something like this:
```
it('should synchronously set initialState before first render', () => {
	const actual = mount(<Preview code={code} evalInContext={evalInContext} />, options);
	const testState = {
		error: 'error',
		count: '42',
	};
	actual.setState(testState);
	expect(actual.state()).toEqual(testState);
});
```
But i pretty sure it's wrong, because it actually renders element before state is changing.

**Comment by sapegin** [comment]
@nicoffee Sorry for the delay. Ideally we shouldn't call methods directly, but I'm not sure it's possible in that case. I'll try to have a look myself.

**Comment by sapegin** [comment]
It actually doesn't work. I've fixed the implementation and have added couple of tests.

**Comment by nicoffee** [comment]
Thank you!

**Pull request merged**
