### PR TITLE
chore(*): drop webpack3 support

### PR DESCRIPTION
**Pull request by stepancar**
https://github.com/styleguidist/react-styleguidist/issues/915

### CODE REVIEW

**Comment by stepancar** [comment]
@sapegin we should mock copy-webpack-plugin to check parameters passed to it constructor.
I tried mock using jest 22 and faced with problems. [This example]( https://facebook.github.io/jest/docs/en/es6-class-mocks.html#the-4-ways-to-create-an-es6-class-mock) not working in jest 22. Its reason why i switched to jest 23.

**Comment by sapegin** [comment]
Thanks! This is awesome! Though we have to wait for CRA2 final release.

Jest 23 is awesome too! Could you please send it as a separate PR? We could merge it right away.

**Comment by stepancar** [comment]
@sapegin we need update package-lock. Now master crashes after update package-lock
Look at https://github.com/styleguidist/react-styleguidist/pull/1030

After it will be closed - I will create Jest23 migration PR

**Comment by stepancar** [comment]
@sapegin , https://github.com/styleguidist/react-styleguidist/pull/1034

**Pull request merged**
