### PR TITLE
Update PlaygroundRenderer.js

### PR DESCRIPTION
**Pull request by kulakowka**
I want to suggest a change in the styles of the playground:

### CODE REVIEW

**Comment by okonet** [comment]
I like the idea! But I think this should be customizable somehow. We might want to discuss features like this in https://github.com/styleguidist/react-styleguidist/issues/354

**Comment by kulakowka** [comment]
@okonet It can be [customized](https://github.com/styleguidist/react-styleguidist/blob/next/docs/Cookbook.md#how-to-change-styles-of-a-style-guide).

**Comment by n1313** [comment]
I have the same kind of background in my project as well, but it's diagonally striped. This one is also good.

**Comment by n1313** [comment]
Although to be honest, I am not sure if this is going to be useful for **most** people. This feature is useful if you are working on some sort of a reusable UI component library which is supposed to work in unpredictable conditions on variety of backgrounds. I doubt this is what the majority of RSG users are building. I think the majority is targeting one environment with a specific background color, and so will have little use for this change, and even might be annoyed by it. I think this change could be a perfect example of how to customise your RSG for the cookbook, or an optional extension in the future, but I'm not 100% sold on it being in the main repo.

**Comment by sapegin** [comment]
Thanks for the pull request. I don’t think it’d be a good default. I agree with @n1313, would you mind sending a new pull request with a cookbook example?

**Pull request closed without merging**
