### PR TITLE
Improve support for objectOf propType

### PR DESCRIPTION
**Pull request by n1313**
This PR improves support for objectOf propType by displaying the name of the type of values and, in case of objectOf(shape), displaying the properties of the shape.

### CODE REVIEW

**Comment by sapegin** [comment]
Screenshot would be very helpful ;-)

**Comment by n1313** [comment]
capture

**Comment by sapegin** [comment]
Looks cool! Will look at the code soon ;-)

**Comment by sapegin** [comment]
Awesome! Thank you very much 🍕

**Pull request merged**
