### PR TITLE
Fix: The build does not work with the copy-webpack-plugin@5.1.0

### LINKED ISSUE #1493: The build does not work with the copy-webpack-plugin@5.1.0
**Current behavior**
The build does not work with empty `assetsDir`

**To reproduce**

1. `assetsDir` is `undefined` 
1. yarn.lock
> ...
> copy-webpack-plugin@^5.0.4:
>   version "5.1.0"
> ...
3.  run `styleguidist build `

Error in terminal:

> ValidationError: CopyPlugin Invalid Options
> 
> options should NOT have fewer than 1 items

**Expected behavior**

Build works

### PR DESCRIPTION
**Pull request by Krivega**
Closes #1493

### CODE REVIEW

**Comment by gabsn** [comment]
Could you merge this asap, we need it to upgrade `react-styleguidist` and fix a security issue present in the subdep `serialize-javascript`.

**Comment by sapegin** [comment]
Is it the same as #1491?

**Comment by sergdenisov** [comment]
@sapegin seems like the same.

**Comment by smashercosmo** [comment]
In latest copy-webpack-plugin this issue is fixed

**Comment by Krivega** [comment]
right, one goal #1491

**Pull request closed without merging**
