### PR TITLE
Add copy-webpack-plugin

### LINKED ISSUE #403: Images in markdown not working in production
I am using create-react-app and have some markdown files in a root `docs` folder that are including images that are located in the same folder, something like this:

`logo`

In dev mode (`styleguidist server`) this works perfectly. But when I build a static site using `styleguidist build` the images are not included in the bundled files. Is there a way to coerce the config to include images for the static build? Or should I move everything into `src`?

### PR DESCRIPTION
**Pull request by gutenye**
Copy static assets into build folder.

Fixes #403

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks for the pull request!

Please update npm lock file (`package-lock.json`) — it should fix the CI.

**Comment by gutenye** [comment]
@sapegin I can't, I use a mirror npm registry url, after `npm install`, it changes the whole `package-lock.json` file, and no idea how to fix it. 
Can you fix it for me?

**Comment by sapegin** [comment]
I’ve updated the lock file but there are a few failing tests ;-|

**Comment by gutenye** [comment]
@sapegin Thanks for updating npm lock file. Test has been fixed.

**Comment by sapegin** [comment]
Don’t worry about the CI failures and bot comments — I’m experimenting a bit here ;-)

**Comment by sapegin** [comment]
I think we should run it only in on production build. Dev server serves static files directly from that folder.

**Comment by gutenye** [comment]
@sapegin Agreed with you, I've updated the code.

**Comment by sapegin** [comment]
I’ve merged it manually because of conflicts. Thanks!

**Pull request closed without merging**
