### PR TITLE
React 15.5 & Prop type updates

### PR DESCRIPTION
**Pull request by ldabiralai**
This updates to using `prop-types` package and changes react versions to 15.5

### CODE REVIEW

**Comment by sapegin** [comment]
Duplicate of #388.

**Comment by ldabiralai** [comment]
Whoops!

**Comment by sapegin** [comment]
We have two PRs for the same thing: one has mysterious merge conflicts and one has mysterious CI failures (this one, it also seems more complete). So I’ll try to merge this one and fix the CI.

**Comment by ldabiralai** [comment]
@sapegin I believe the tests are failing due to Enzyme issues. It's waiting on https://github.com/airbnb/enzyme/pull/876 to be released.

Sorry, forgot to mention that in my initial PR description.

**Comment by sapegin** [comment]
They are going to make a release soon so I’d wait a bit.

**Comment by sapegin** [comment]
It actually completly breaks Styleguidist because of https://github.com/reactjs/react-docgen/issues/171, so I’m reverting this for now.

**Comment by sapegin** [comment]
Waiting for https://github.com/reactjs/react-docgen/pull/172

**Comment by sapegin** [comment]
Finally I could make it work ;-|

**Comment by ldabiralai** [comment]
Awesome, thanks! 👍

**Pull request merged**
