### PR TITLE
Fix: Exported typings

### PR DESCRIPTION
**Pull request by elevatebart**
After trying to use the new typings of v11, I figured the whole namespace thing was a mistake.
None of the types were exported properly and nothing was actually usable.

I want to pull your attention to a file that would represent a breaking change: `src/script/index.ts`
In order to export the types with es6 in mind, I transformed the `module.exports` into an `export default` and added the typings in there. 

The rest of it is simply adding `import * as Rsg from 'typings'` to a lot of files.

### CODE REVIEW

**Comment by elevatebart** [comment]
inspiration : https://medium.com/@mweststrate/how-to-create-strongly-typed-npm-modules-1e1bda23a7f4

**Comment by sapegin** [comment]
Uff, that's a lot of changed files. Let me know when you're done with CI ;-)

**Comment by elevatebart** [comment]
Before merging this one make sure you merge #1549 
I will need to solve some conflicts before this can be done.

**Comment by elevatebart** [comment]
@sapegin I am done with the CI, should I simply click merge ?

**Pull request merged**
