### PR TITLE
Feat: build progress

### PR DESCRIPTION
**Pull request by evillt**
Hi

I add a `webpack.ProgressPlugin` to `make-webpack-config.js` for let user know current building progress.

The `printServerInstructions()` and `openBrowser()` behaviors will works after building completed.

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks! Could you add a GIF, how this looks?

**Comment by evillt** [comment]
> Thanks! Could you add a GIF, how this looks?

Looks like this.🤔

react-styleguidist-progress 2019-04-18 16_22_39

**Comment by sapegin** [comment]
Actually we already have a spinner, and this plugin just clutters the terminal with useless information, so I'm going to close this. Thanks for the PR anyway!

**Comment by evillt** [comment]
Okay, I just feel confused cuz while I starting server, then terminal show the URLs in seconds but it actually can not access.

My point is: show the URLs after the building is completed.

Feel sorry to spend your time.

**Pull request closed without merging**
