### PR TITLE
Migrate to react-codemirror2

### LINKED ISSUE #573: Migrate to react-codemirror2
Since the original react-codemirror is not maintained anymore and the author isn’t responding even to direct messages, and there’s a bug that [affects our users](https://github.com/styleguidist/react-styleguidist/issues/527).

https://github.com/scniro/react-codemirror2

/cc @scniro @misantronic @smashercosmo

### PR DESCRIPTION
**Pull request by scniro**
Fixes #573.

### CODE REVIEW

**Comment by scniro** [comment]
This project is heavily sculpted to a linux work environment and I had a lot of errors being thrown locally on my windows machine, specifically, pathing and SHA concerns regarding tests and `package-lock.json.` I was able to verify the package works as expected, however I was unable to verify tests or update the `package-lock.json` file without causing a waterfall of issues due to being on Windows. Regardless, the meat of the migration is here and I'd appreciate if you can implement the specifics I am unable to at the moment. Thank you!

**Comment by sapegin** [comment]
What exactly do you mean by “heavily sculpted to a linux work environment”, how can we fix that?

**Comment by scniro** [comment]
A few things - even before getting into it in your contributing guidelines, the following command fails on Windows because `&` is not a valid operator.
 
    npm run compile:watch & npm start

But that'd be easy enough to clarify or not even worry about. For testing/snapshot creation - all of the pathing borked. A lot of errors similar to the following...\

> Expected value to equal:
>       "/"
>     Received:
>       "C"
> 

Due to being on Windows and _something somewhere_ is looking for my C drive. I can always clone this down to a linux envurinment but I usually find myself on the Windows side. I'm sure we could fix this by using tools such as [cross-env](https://www.npmjs.com/package/cross-env) and investigate what Jest is going with pathing and why it's failing.

In the package lock, the integrity hash is converting all packages to a sha1 on my machine after updating the one package. For example...


~~"integrity": "sha512-4AH6Z5fzNNBcH+6XDMfA/BTt87skxqJlO0lAh3Dker5zThcAxG6mKz+iGu308UKoPPQ8Dcqx/4JhujzltRa+hQ==",~~
"integrity": "sha1-D8Z9fBQYJd6UKC3VNr7GubzoYKs="

 I honestly don't know the implication of this, if any, but I opted to not commit it.

Perhaps this PR was just more of a hassle than it is worth since I changed only a few lines and am being berated by environment errors. If you care to nail down this further I'd be open to resolving it across the board with you so any future Windows users won't be burdened by similar issues.

**Comment by sapegin** [comment]
This thing with paths is weird but it maybe [here](https://github.com/styleguidist/react-styleguidist/blob/master/loaders/utils/__mocks__/requireIt.js). Would be nice if you could debug it.

The thing with `package-lock.json` is probably not connected to Windows — I’ve seen this before and have no idea why it happens.

/c @n1313 Are you on Windows? Do you have any issues with Styleguidist now?

**Comment by scniro** [comment]
@sapegin I can totally look into debugging this and getting everything resolved locally. I'll spend some time later today and send a fresh PR when I (hopefully) smooth everything out. Will keep you posted.

**Comment by scniro** [comment]
@sapegin hey again. I kind of ran around in circles on a fresh clone trying to get the tests to pass. I'm going to set this down for now as it's looking like it'll be more involved to get playing nicely with Windows. Can you merge this PR and check my changes locally and commit if all looks well?

**Comment by sapegin** [comment]
OK, I’ll have a look — right now it’s failing on CI and it looks like it doesn’t work at all. But it maybe because of the old lock file.

**Comment by sapegin** [comment]
They’ve changed a CSS class name for the wrapper, that’s why tests were failing. Let’s wait for the CI again and I’ll merge it.

**Comment by sapegin** [comment]
Merging :shipit:

**Pull request merged**
