### PR TITLE
Chore: Remove remnants of Flow

### PR DESCRIPTION
**Pull request by sapegin**
Remove pieces of Flow left after the TypeScript migration.

### CODE REVIEW

**Comment by elevatebart** [comment]
I believe we have to keep `@babel/preset-flow` for some tests.
Apart from that and the small alert, I see no pb with this one.

**Comment by sapegin** [comment]
We'll need to updates the docs then: https://react-styleguidist.js.org/docs/api.html

**Comment by elevatebart** [comment]
I agree, I will take care of it before tomorrow.

Bart Ledoux

Join me on LinkedIn
Or as @elevatebart on Discord, Twitter and Github

**Comment by elevatebart** [comment]
I updated the documentation using imports instead of requires. I hope you find it useful.
It might be useful to add a note about NodeJs not accepting es6 imports. There is a non obvious need for transpilation.

**Comment by sapegin** [comment]
I think we can also reexport it as CommonJS in a separate module to avoid breaking changes.

**Comment by elevatebart** [comment]
I did my best. I hope you like it.

**Comment by sapegin** [comment]
I'm not sure the `module` field is useful here, I think it's only used by bundlers, but good enough for now ;-) Thanks for the changes!

**Pull request merged**
