### PR TITLE
Honor default exports over named exports

### PR DESCRIPTION
**Pull request by Lazyuki**
When you have a component like 

```tsx
import React from 'react';
import styled from 'styled-components';

export const C: React.FC = () => {
  ...
}

const StyledC = styled(C)``;

export default StyledC;
```
so that you can use non-styled (name-exported) components for testing, styleguidist picks up the named export instead of the default export and breaks the styling in examples. 

If I understand [this part of the doc](https://react-styleguidist.js.org/docs/components.html#default-vs-named-exports) correctly, isn't this supposed to be the case? As in it will try to find
1. default exports 
2. if not found => single named export
3. if not found => named export with the same name

I'm aware there are a few workarounds to get my example above working, but just in case the current behavior isn't intended.

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks for the pull request!

I guess you're right, this looks more reasonable. You need to fix the CI though ;-)

**Comment by elevatebart** [comment]
@sapegin this could be a breaking change and we have 11 around the corner, do you think it should be part of this new major version?

**Comment by sapegin** [comment]
@elevatebart Yeah, make sense! If it's going to be ready soon.

**Comment by Lazyuki** [comment]
@sapegin thanks for the merge. Do you have a rough ETA on v11?

**Comment by sapegin** [comment]
There's a beta version:

https://github.com/styleguidist/react-styleguidist/releases/tag/v11.0.0-beta2

**Comment by Lazyuki** [comment]
oh thanks!

**Comment by Lazyuki** [comment]
Hey @sapegin, I see that the 11 branch is updated with current master+new v11 features. Could you release v11.0.0-beta3 with these updated changes on master? Much appreciated!

**Comment by sapegin** [comment]
I think I'll try to make a final release with what we have in the 11 branch.

**Comment by Lazyuki** [comment]
Oh that's great news!

**Pull request merged**
