### PR TITLE
WIP: Small UI Improvements Phase 2

### LINKED ISSUE #426: UI improvements proposal (UI 2.0)
We keep adding new function and new “buttons” to the UI and right now it’s inconsistent and far from perfect. Adding more features (and there are plans and wishes to do that) will most likely destroy user experience completely. I was thinking about that for a long time and here are my thoughts.

Goals I want to solve in this issue:

* Improve developer experience (component development process);
* Simplify and streamline the UI;
* Add UI extension points for plugins.

Styleguidist UI consists of these three “levels” (and actions you can do on each level, with some future plans):

* Global (toggle sidebar, toggle props/description, switch background, close isolation = go home);
* Component / section (get anchor link, open in isolation);
* Example (open in isolation, toggle code visibility, show snapshots).

As a possible solution I see something like this:

ui2

Sorry for my drawing skills but basically we’ll have toolbars for each “level” that could be possible to extend from plugins plus (also extendable) tab bar for each example (this was already discussed in a relation to the plugin API).

Related issues: #354, #333, #327, #424, #421, #235.

Any feedback? Some design help would be very useful here ;-)

### PR DESCRIPTION
**Pull request by SaraVieira**
**The latest demo: https://styleguide-vwetycents.now.sh/**

What is done:

* Carret added on Props to help people understand that it's a clickable drop-down
* Sidebar now closes and opens with the click of a button 🎉
* Toggle props button is in place
* Responsive Navigation, when the user is on a phone the navigation will hide and in his place the user will only see the show sidebar button to toggle it.

What I need help:

* Understand the best way to make toggle props master button work
* Fix commented test
* Feedback 

Closes #426 & #424

### CODE REVIEW

**Comment by SaraVieira** [comment]
I know the build is failing , any idea what values used to be ?

**Comment by sapegin** [comment]
> I know the build is failing

It says the build is now two times bigger than it used to be.

**Comment by SaraVieira** [comment]
- [ ] - Code tab should look the same way and the arrow icons should be inside the tab button component. 
- [ ] - remove yarn lock file.
- [ ] - Toggle props is hidden in isolated mode

On it !

**Comment by ankri** [comment]
I really like the new looks! Could you please also add a `title` attribute to all the toggles and buttons? I don't think there is a need for a separate tooltip dependency but `title`s for example would have helped me to understand what this button is for:

image

**Comment by sapegin** [comment]
Yeah, we just use `title` for all other toolbar buttons.

**Comment by sapegin** [comment]
I’m not giving much feedback about the code because we’re not yet sure how everything should look. But I’ll read it carefully later ;-)

> I know but why ? I didn't even install anything

That’s something weird. I only see two new icons, something must be wrong here. I’ll take a look later.

> You think the click should make changes to the theme ?

I don’t think so. Maybe we should hide the header and show component name somewhere else, like on a fixed toolbar near buttons to toggle sidebar and toggle uberisolated mode. I’m open for ideas ;-)

/cc @okonet @kof @tizmagik @n1313 @stepancar

**Comment by SaraVieira** [comment]
@sapegin I could do a tooltip in just CSS and the content in the before, what you think?

**Comment by SaraVieira** [comment]
I'll do some iterations of that and send some screenshots :)

**Comment by sapegin** [comment]
Maybe a good idea but as a separate PR ;-)

**Comment by sapegin** [comment]
Also use `ToolbarButton` bur buttons — right now it’s just an image.

**Comment by SaraVieira** [comment]
What do you mean by the last comment?

**Comment by sapegin** [comment]
You’re attaching an `onClick` handler to an image which make them inaccessible, inconsistent with other toolbar buttons, you have to write a lot of extra styles, and we already have a component for toolbar buttons.

**Comment by SaraVieira** [comment]
Oh! Okay, cool 😃

**Comment by SaraVieira** [comment]
@ankri @sapegin Added the toolbarButton and it looks waaaay better actually :p 

thank you for reminding me 👍 

https://styleguide-vwetycents.now.sh/

Will take a lot at some possible mods tomorrow for focus mode :)

**Comment by okonet** [comment]
@SaraVieira here is my thoughts on the UI:

1. I think the location of the buttons in the sidebar is odd. It was merely an accident I noticed them.
1. I'm wondering why do we even need the hide sidebar button?
1. The second button doesn't do anything for me...

**Comment by SaraVieira** [comment]
@okonet Thanks for the feedback! 🙌

Regarding the second button it's true it doesn't do anything yet :(

Where do you think it would be a better position for them?

About the hiding the sidebar it has come in handy for me a couple of times but yes it's a niche problem

**Comment by sapegin** [comment]
@SaraVieira Any particular use cases for manually hiding the sidebar? I really want the uberisolated mode ;-)

**Comment by SaraVieira** [comment]
The main use case is mobile like it does right now, besides that it could be useful if you want to work in focus mode.

Now that I think about its more of a pretty thing then an actually necessity on desktop 🙁

**Comment by sapegin** [comment]
But do you really need to see all components in that mode?

**Comment by SaraVieira** [comment]
Mostly not 🙁

Maybe the sidebar removal in desktop should enable focus mode instead of having two buttons

**Comment by SaraVieira** [comment]
Btw, @sapegin I pinged you on slack

**Comment by sapegin** [comment]
I think the main question here is what would be the best experience for developing components?

For me it would be uberisolation mode: 

* one component
* all examples visible at the same time
* No distractions like a huge heading, pathline, etc.
* Togglable side paddings in example playgrounds (for responsive testing)

**Comment by okonet** [comment]
Yes, let's approach the problem with real use cases and not with the UI first. I'll write down my thoughts on the DX as soon as I get some more time. Sorry for delays :-/

**Comment by tizmagik** [comment]
Yes, for me the most important DX consideration is lack of chrome (padding, etc) for responsive testing.

**Comment by SaraVieira** [comment]
@tizmagik I can tackle that and just get a better mobile experience for testing

@okonet Not a problem man! Get back to this when you have time :)

**Comment by sapegin** [comment]
I’d suggest to split this PR otherwise we’ll never finish it because there are so many things that needs further discussion.

> Carret added on Props to help people understand that it's a clickable drop-down

+1 from me.

> Sidebar now closes and opens with the click of a button 🎉

Not sure we really need that.

> Toggle props button is in place

That’s the whole discussion of the uberisolated mode.

> Responsive Navigation, when the user is on a phone the navigation will hide and in his place the user will only see the show sidebar button to toggle it.

This is useful I think but since we’re not sure about the toggle sidebar button I’m not sure how it should work.

What do y’ll think?

My thought and wishes about uberisolation:

image 2017-11-17 at 1 14 49 pm

Any feedback?

**Pull request closed without merging**
