### PR TITLE
Add prop-types package

### PR DESCRIPTION
**Pull request by kulakowka**
#380 done :white_check_mark:

### CODE REVIEW

**Comment by sapegin** [comment]
Could you please use the master branch?

**Comment by okonet** [comment]
@sapegin you can edit the branch yourself. I just did and now it's against master.

**Comment by okonet** [comment]
Oh I guess it doesn't help because of all these conflicts 🤦🏻‍♂️

**Comment by sapegin** [comment]
Yeah, looks like the only way is to submit a new PR. @kulakowka sorry for the inconvenience ;-|

**Comment by kulakowka** [comment]
Tell me, where can I see conflicts?

**Comment by kulakowka** [comment]
I can make changes again in the master branch if you want.

**Comment by sapegin** [comment]
Yeah, I think it would be simpler than resolving a dozen of conflicts.

**Pull request closed without merging**
