### PR TITLE
changed es6-promise/auto to es6-promise.polyfill() to avoid build error

### PR DESCRIPTION
**Pull request by davidsims9t**

### CODE REVIEW

**Comment by sapegin** [comment]
What kind of errors you have? According to the docs it should be the same — https://github.com/stefanpenner/es6-promise#auto-polyfill

**Comment by davidsims9t** [comment]
I'm getting an error that the path es6-promise/auto doesn't exist. It only occurs after updating to react-styleguidist 5.3.2.

**Comment by sapegin** [comment]
This is weird because it would break CI and won’t work for everybody else. Could it be something unusual in your webpack config?

**Comment by davidsims9t** [comment]
I suppose it could be something in Webpack, but it's strange that it's only when I upgrade to 5.3.2 that I see this error.

**Comment by sapegin** [comment]
Could you run `npm ls es6-promise`? It looks like it uses a different version of the package — may be because of `resolve.modules` in webpack config.

**Pull request closed without merging**
