### PR TITLE
examples preprocessor and case insensitive settings for example

### PR DESCRIPTION
**Pull request by stepancar**
https://github.com/styleguidist/react-styleguidist/issues/269
https://github.com/styleguidist/react-styleguidist/issues/517

### CODE REVIEW

**Comment by stepancar** [comment]
@sapegin , added examplesPreprocessor setting to config which allow to override/customize examples

**Comment by sapegin** [comment]
Awesome, thanks! I don’t like the name though, but don’t have any better ideas now. Will think ;-)

**Comment by sapegin** [comment]
Thanks! We could change the name later, still have not better ideas ;-|

**Comment by stepancar** [comment]
Why you don't like this name?

**Comment by sapegin** [comment]
“Preprocessor” is way to complex word for a simple function ;-)

**Comment by stepancar** [comment]
hm)
I exampleReplacer, exampleOverrider, exampleUpdater?
or just
```
getExample({lang, content, settings})=>
    ({
        lang,
        content,
        settings
    })
```

**Comment by sapegin** [comment]
I’d try something like `updateExample`. Better matches other settings.

**Comment by stepancar** [comment]
@sapegin updarted in six branch

**Pull request merged**
