### PR TITLE
Hash JS assets in production build

### LINKED ISSUE #371: Hash JS assets in production
When deploying a styleguide to production, the JS assets are not hashed / fingerprinted. When using a CDN, this means the assets are difficult to update since you have to manually expire the assets.

Relevant lines: https://github.com/styleguidist/react-styleguidist/blob/master/scripts/make-webpack-config.js#L27-L30

Below the above lines, there is a section for `isProd`. Adding a hash to the filename and chunk filenames should fix this issue. For reference, this is how create-react-app handles it: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js#L70-L71

If this is something you're interested in adding to the library, I'd be happy to create a PR for it 😄

### PR DESCRIPTION
**Pull request by green-arrow**
Fixes #371

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks for the PR!

One note: we probably should remove old files otherwise `bundle` folder will grow.

**Comment by green-arrow** [comment]
@sapegin - should that be part of this PR? I can always bring in [rimraf](https://github.com/isaacs/rimraf) and just remove the styleguide directory before the build starts.

**Comment by green-arrow** [comment]
@sapegin - Just FYI, I have a commit locally that uses `rimraf` to remove the `styleguide/build` directory before every build. If you'd like that to be in this PR, just let me know and I'll go ahead and push it.

**Comment by sapegin** [comment]
Probably better to use [clean-webpack-plugin](https://www.npmjs.com/package/clean-webpack-plugin) to keep everything in webpack config.

**Comment by green-arrow** [comment]
@sapegin - alrighty. Should that be a separate PR or included here?

**Comment by sapegin** [comment]
Up to you, I’m fine either way ;-)

**Comment by green-arrow** [comment]
@sapegin - I'll just pop it in this commit then 😄 

Give me a couple minutes and I'll push it out.

**Comment by green-arrow** [comment]
@sapegin @okonet - Changes for cleaning up the `build` directory are pushed. Let me know if you see anything that needs changed / added.

**Comment by sapegin** [comment]
Awesome, thanks!

**Comment by sapegin** [comment]
I’m making the same mistake for the second time — missing that a new dependency was added to the wrong group (`dependencies` / `devDependencies`) because GitHub doesn’t show enough code in the diff to spot it 🤔

New path release should fix that very soon.

**Pull request merged**
