### PR TITLE
Fix: Slot onClick passes correct id

### LINKED ISSUE #971: Slot onClick handler calls previous slot's onClick
There's a small coding bug in `Slot.js` where `props` is reassigned in a loop, so the `onClick` handler of all slots after the first end up delegating back to the first slot's `onClick`.

It's hard to produce a demo for this, it's more future proofing for custom slots. I'll create a PR with a unit test.

### PR DESCRIPTION
**Pull request by kidkuro**
Fixes #971.

Updated `Slot` `onClick` unit test to verify that correct id passed for second slot, and fixed code to make this pass.

### CODE REVIEW

**Comment by kidkuro** [comment]
The failed check doesn't appear to have anything to do with my code change. 

#974, #976 and #978 have all failed for the same reason.

It appears #963 was raised with the same problem.

Since `Object.entries` isn't in the source code, my guess is that could be that Babel is transpiling code to use it, expects a browser environment that supports it, or has been polyfilled with core-js... but is executing in a test in Node on an agent with and older version of Node that [doesn't support it](https://node.green/#ES2017-features-Object-static-methods-Object-entries).

**Comment by sapegin** [comment]
Sound be fixed in master now.

**Comment by kidkuro** [comment]
Awesome, thanks. I'll merge and push up to each PR again.

**Comment by sapegin** [comment]
Looks like I'm missing something, how does this fix the issue? Shouldn't it behave the same way it was before renaming?

**Comment by kidkuro** [comment]
The loop reassigned the `props` argument inside the loop to a new object... but also extracted `const { onClick } = props;` Which means, the second time round the loop `onClick` referred to the first slot's `onClick` not the `onClick` passed to the function. And the first slot's `onClick` is a delegate function that passes the first slot's `id` in a closure.

Try running the test without the code change, you'll see it expects to get `'two'` but receives `'one'`

By the way, I would suggest turning on the eslint rule to prevent reassigning arguments, that will prevent this sort of bug.

**Comment by sapegin** [comment]
Oh, I see!

> By the way, I would suggest turning on the eslint rule to prevent reassigning arguments, that will prevent this sort of bug.

That sounds good, but may need some changes in the code ;-)

**Comment by sapegin** [comment]
Could we try to make this code more explicit?

```js
	const rendered = fills.map((fill, index) => {
		// { id: 'pizza', render: ({ foo }) => <div>{foo}</div> }
		const { id, render } = fill;
		if (id && render) {
			// Render only specified fill
			if (onlyActive && id !== active) {
				return null;
			}

			const { onClick } = props;
			const fillProps = {
				...props,
				name: id,
				// Set active prop to active fill
				active: active && id === active,
				// Pass fill ID to onClick event handler
				// eslint-disable-next-line react/prop-types
				onClick: onClick && ((...attrs) => onClick(id, ...attrs)),
			};

			const Fill = render;
		        return <Fill key={index} {...fillProps} />;
		}

                // fill is a component 
        	const Fill = fill;
		return <Fill key={index} {...props} />;
	});

```

**Comment by sapegin** [comment]
Or probably we should just remove the simple form and require ID for every fill. I think the simple form is used only here now:

https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/slots/index.js#L11

**Comment by kidkuro** [comment]
Sure, I'll update that to have an id

**Comment by sapegin** [comment]
I can increase it even more, but not sure it will help ;-/

**Comment by sapegin** [comment]
It's actually different, this is the flaky one and it's passing:

> ✓ changes the render after code change (1089ms)

And the failing test case is:

> 1) Styleguidist core shows single component in isolated mode:
>     Uncaught Error: Script error.

**Comment by sapegin** [comment]
Which is probably related to your latest changes, and the test looks fine for me:

https://github.com/styleguidist/react-styleguidist/blob/7f5137e2484eb861371ede7e6e8f718e97ff9d06/test/cypress/integration/core_spec.js#L12-L18

**Comment by sapegin** [comment]
Where did you put that `NO_PROXY`? ;-/ We need some docs how to run and debug these tests locally, but they actually right: the isolated mode is broken now because the `name` is overwritten by the fill name. It may be not that easy to fix though…

**Comment by kidkuro** [comment]
In order to access the internet on my work network you must go via a proxy, so I have an `HTTP_PROXY` environment variable set, but I never bothered also setting a `NO_PROXY` environment variable to exclude localhost... since it didn't see to cause me any issues. However, running Cypress wasn't working, so I exported `NO_PROXY=localhost` and that allowed Cypress to run.

However, all the tests passed for me. I will have another go, but if I can't sort it out, I think I should roll back the second commit. That refactoring is unrelated to the original bugfix, and it should probably be left to a separate, more considered PR.

**Comment by kidkuro** [comment]
Ok, I reproduced the error... not sure what happened last time. I have no idea what I am looking at... but... I'll give it a go.

**Comment by kidkuro** [comment]
Ok, so there is a fundamental difference between the tabbutton/tabpanel slots that require an id to associate the pair, which is used as the name, and the Isolate button.

I'm going to revert the second commit. I don't really understand the idea behind the slots, but I have a feeling that it might be too generic a pattern to properly implement both of those purposes. In any case, if it needs to change, it should be a separate ticket.

**Comment by sapegin** [comment]
OK, let's do that, and then I'll try to cherry pick your latest commits and fix that. The code is really confusing now ;-|

**Comment by kidkuro** [comment]
Ha! OK... The changes tab shows the actual change. Its only the very first commit. If you'd like I can just close this PR, create a fresh branch, and a new PR.

**Comment by kidkuro** [comment]
Oh, you've already merged. Cool 👍

**Comment by sapegin** [comment]
Could you open a new PR with the changes you've reverted? That could be a good start and I could help with finishing it.

P. S. You can create a new branch directly at this repo, no need to fork it ;-)

**Pull request merged**
