### PR TITLE
Feat: Use Text component for rendering Markdown text, 'em', and 'strong'

### PR DESCRIPTION
**Pull request by ryanoglesby08**
Continuing on with [Issue #613](https://github.com/styleguidist/react-styleguidist/issues/613)

### CODE REVIEW

**Comment by ryanoglesby08** [comment]
Re: merge conflict --> O shoot, will fix the merge conflict.

Re: unrelated changes --> Yes I found that odd, when I ran `yarn test`, which triggers `yarn lint` I got linting errors that needed to be fixed. That is why there are unrelated changes. Should I just revert those changes and leave the linting errors alone?

**Comment by sapegin** [comment]
It looks like your Prettier version is different, or what was the linting error? Try to use npm so it would pick up npm lock file to be sure that versions are the same.

**Comment by ryanoglesby08** [comment]
I blew away node_modules and installed with npm. Running `npm run lint` still creates the same changes in "scripts/create-server.js"...

**Comment by sapegin** [comment]
That’s weird, when I run npm test in master I don’t see any changes. It looks like your master isn’t the latest. Otherwise the code is good, I like it!

**Comment by ryanoglesby08** [comment]
Trying again with a new PR...

**Pull request closed without merging**
