### PR TITLE
Docs: IE11 example

### PR DESCRIPTION
**Pull request by smashercosmo**
Here is minimal example of react-styleguidist that works in IE11

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks! FAQ could be a better place for that.

Please add explanation why it works.

**Comment by smashercosmo** [comment]
@sapegin do you want me to add FAQ section in addition to example or instead?

**Comment by sapegin** [comment]
Instead, I think it would be enough and will be easier to explain how it works and why.

Artem Sapegin, sapegin.me

**Comment by abhishekdev** [comment]
I was not able to get the generated site to comeuppance in IE11 with v9.0.7. IE 11 throws `Syntax Error` on `acorn-jsx` code. To be precise, IE11 fails on the `class` keyword on [this line from acorn-jsx](https://github.com/RReverser/acorn-jsx/blob/6697d3407221a58e23d040b4059f20eb045247a5/index.js#L72). There might be other errors as well, but it bails out on the first.

I ran a build on @smashercosmo's  branch by running

```sh
node lib/bin/styleguidist.js server --config examples/ie11/styleguide.config.js
```

This build throws the following compiler warnings and It does not seem the site is served( irrespective of browser). Am I missing something? cause it seems the warning and the IE11 issue may be related and *maybe* the target files from `acorn-jsx` & `regexpu-core` may not have been processed at all.

```
 WARN  Compiled with warnings

./node_modules/buble/dist/buble-browser.es.js
Attempted import error: 'acorn-jsx' does not contain a default export (imported as 'acornJsx').
 @ ./lib/client/utils/compileCode.js
 @ ./lib/client/rsg-components/ReactExample/ReactExample.js
 @ ./lib/client/rsg-components/ReactExample/index.js
 @ ./lib/client/rsg-components/Preview/Preview.js
 @ ./lib/client/rsg-components/Preview/index.js
 @ ./lib/client/rsg-components/Playground/Playground.js
 @ ./lib/client/rsg-components/Playground/index.js
 @ ./lib/client/rsg-components/Examples/Examples.js
 @ ./lib/client/rsg-components/Examples/index.js
 @ ./lib/client/rsg-components/Section/Section.js
 @ ./lib/client/rsg-components/Section/index.js
 @ ./lib/client/rsg-components/Sections/Sections.js
 @ ./lib/client/rsg-components/Sections/index.js
 @ ./lib/client/rsg-components/StyleGuide/StyleGuide.js
 @ ./lib/client/rsg-components/StyleGuide/index.js
 @ ./lib/client/utils/renderStyleguide.js
 @ ./lib/client/index.js
 @ multi core-js ./lib/client/index ./node_modules/react-dev-utils/webpackHotDevClient.js
./node_modules/buble/dist/buble-browser.es.js
Attempted import error: 'regexpu-core' does not contain a default export (imported as 'rewritePattern').
 @ ./lib/client/utils/compileCode.js
 @ ./lib/client/rsg-components/ReactExample/ReactExample.js
 @ ./lib/client/rsg-components/ReactExample/index.js
 @ ./lib/client/rsg-components/Preview/Preview.js
 @ ./lib/client/rsg-components/Preview/index.js
 @ ./lib/client/rsg-components/Playground/Playground.js
 @ ./lib/client/rsg-components/Playground/index.js
 @ ./lib/client/rsg-components/Examples/Examples.js
 @ ./lib/client/rsg-components/Examples/index.js
 @ ./lib/client/rsg-components/Section/Section.js
 @ ./lib/client/rsg-components/Section/index.js
 @ ./lib/client/rsg-components/Sections/Sections.js
 @ ./lib/client/rsg-components/Sections/index.js
 @ ./lib/client/rsg-components/StyleGuide/StyleGuide.js
 @ ./lib/client/rsg-components/StyleGuide/index.js
 @ ./lib/client/utils/renderStyleguide.js
 @ ./lib/client/index.js
 @ multi core-js ./lib/client/index ./node_modules/react-dev-utils/webpackHotDevClient.js
```

**Comment by abhishekdev** [comment]
I could make the example by @smashercosmo work! The initial issue I came across turned out to be related to npm and how it dedupes packages. 

A few other scenarios I came across while trying to make it work for my project:

- Using custom presets in babel config. This can impact the workability of the example. e.g. Babel 7 requires a file named `babel.config.js` (vs. `.babelrc.js`) to process dependencies.
- Ability to work with [nested webpack rules](https://webpack.js.org/configuration/module/#nested-rules)

FWIW: Based on @smashercosmo  findings, here is [the config that worked for me](https://github.com/abhishekdev/react-styleguidist/blob/487660c1c2812705015e5b7652c0c9beba02398f/examples/ie11/styleguide.config.js#L16-L34)

```js
const TRANSFORMS_FOR_IE11 = {
  test: /\.jsx?$/,
  include: /node_modules\/(?=(acorn-jsx|regexpu-core|unicode-match-property-ecmascript|unicode-match-property-value-ecmascript|react-dev-utils|ansi-styles|ansi-regex|chalk|strip-ansi)\/).*/,
  use: {
    loader: "babel-loader",
    options: {
      presets: [
        [
          "@babel/preset-env",
          {
            targets: {
              ie: "11"
            }
          }
        ]
      ]
    }
  }
};
webpackConfig.module.rules = [
  TRANSFORMS_FOR_IE11,
  ...webpackConfig.module.rules
];

```

**Comment by nlt2390** [comment]
> I could make the example by @smashercosmo work! The initial issue I came across turned out to be related to npm and how it dedupes packages.
> 
> A few other scenarios I came across while trying to make it work for my project:
> 
>     * Using custom presets in babel config. This can impact the workability of the example. e.g. Babel 7 requires a file named `babel.config.js` (vs. `.babelrc.js`) to process dependencies.
> 
>     * Ability to work with [nested webpack rules](https://webpack.js.org/configuration/module/#nested-rules)
> 
> 
> FWIW: Based on @smashercosmo findings, here is [the config that worked for me](https://github.com/abhishekdev/react-styleguidist/blob/487660c1c2812705015e5b7652c0c9beba02398f/examples/ie11/styleguide.config.js#L16-L34)
> 
> ```js
> const TRANSFORMS_FOR_IE11 = {
>   test: /\.jsx?$/,
>   include: /node_modules\/(?=(acorn-jsx|regexpu-core|unicode-match-property-ecmascript|unicode-match-property-value-ecmascript|react-dev-utils|ansi-styles|ansi-regex|chalk|strip-ansi)\/).*/,
>   use: {
>     loader: "babel-loader",
>     options: {
>       presets: [
>         [
>           "@babel/preset-env",
>           {
>             targets: {
>               ie: "11"
>             }
>           }
>         ]
>       ]
>     }
>   }
> };
> webpackConfig.module.rules = [
>   TRANSFORMS_FOR_IE11,
>   ...webpackConfig.module.rules
> ];
> ```

Using react-styleguidist@9.1.7, got IE error and this code works for me.

**Comment by stonebk** [comment]
I also had to add `estree-walker` to the includes to get this to work for me in `react-styleguidist@9.1.11`

**Comment by kopax** [comment]
Could this be included by default in the configuration so everyone use a styleguidist compatible with IE11?

**Pull request closed without merging**
