### PR TITLE
Feat: Hide errors while typing in code editor

### PR DESCRIPTION
**Pull request by UsulPro**
Hi! First of all, thank you for a great project. I used storybook for my projects, and now I really like styleguidist and I'd like to spend some time for working on using these two projects together

Regarding this PR, I noticed that while typing in the code editor some errors can appear in the component preview. It could be a bit annoying in case if you just haven't a bracket closed for example. So this PR will change it to show an error only if you remove focus from the editor and if you still in editor only red marker will appear (it can be customized via css). If there was an error before you focus the code editor, it behaves as usual

[screenview](http://recordit.co/tHF1tlv7nj)

### CODE REVIEW

**Comment by sapegin** [comment]
Hi Oleg! Thanks for the pull request!

I’m afraid such behavior will annoy more people than the current behavior ;-/ Personally I want to know if I have an error in the code and what / where is this error. I also think that showing an obsolete state in the preview and requiring users to check the color of the border isn’t very good idea.

You can increase `previewDelay` to show errors later. 

I’ll keep the PR open for a while — maybe I’m wrong and other contributors will say so ;-)

**Comment by kof** [comment]
Why do you save your file with errors? In any case you need to fix that error and showing errors as fast as possible is a good thing.

**Comment by okonet** [comment]
I agree on showing errors as soon as possible. Don't think this should be over complicated: if there is an error in the code then it should be displayed.

**Comment by UsulPro** [comment]
Thank you for response, guys! I don't mind, I think it could be closed now 😄

**Comment by tizmagik** [comment]
Hm... maybe just me, but I see value in this PR.

I do find it sort of jarring when editing code in the CodeMirror box it jumps around and shows a redbox because you haven't yet typed the closing bracket or whatever. I can certainly see the need to show the error when you're editing the actual source file and hitting save, but this is solving a different use case (iterating in the CodeMirror box). I also think it's kind of clever to show the error on blur -- maybe we can sow the error after some onChange throttle in the CodeMirror box in addition to the on blur?

This seems useful... am I missing something?

**Comment by sapegin** [comment]
@tizmagik That’s exactly how it supposed to work: [debounce changes in textarea](https://github.com/styleguidist/react-styleguidist/blob/d0646ae50d9a33cfcfe3acb46861f4f303d41a6e/src/rsg-components/Playground/Playground.js#L62-L66).

**Comment by tizmagik** [comment]
@sapegin right! I can see how that sort of does what's here but it's nice to be able to see valid changes shown immediately and only delay/move errors so you don't lose your place on the page. 

But maybe it's just me and @UsulPro 😅🤷‍♂️

**Comment by kof** [comment]
We lack the right solution here, its obviously not removing fast errors, its making the errors reading experience better without jumps.

**Comment by sapegin** [comment]
@tizmagik That might work too though may unnecessary complicate the code ;-)

@kof I agree that current solution is not perfect. Do you have any ideas how to improve it?

**Comment by kof** [comment]
Mb separate view for errors, like a sidebar console

**Comment by tizmagik** [comment]
Maybe a compromise here would be to retain the height of the example preview on errors (and set it again when there's valid code)?

That would nicely solve the pain point I have with the page jumping on errors as I'm typing. Thoughts?

**Comment by kof** [comment]
Btw why not to rethrow errors into the dev tools console?

**Comment by sapegin** [comment]
@kof That would hide them from the user ;-)

Maybe @okonet has some ideas.

**Comment by kof** [comment]
Or render an overlay above the component in its previous working state and write the error there, so that there is no jumps and additionally throw it into the dev tools console so that we see the stack trace which is currently not available and I already had some pain with this.

**Comment by sapegin** [comment]
That’s closer, yeah ;-) The only issue is when error is much taller than the rendered component.

**Comment by kof** [comment]
> That’s closer, yeah ;-) The only issue is when error is much taller than the rendered component.

scroll it, set min height

**Comment by tizmagik** [comment]
Could be scrollable

**Comment by sapegin** [comment]
In case with no previous render or some tiny component that won’t work. `min-height` would cause the same jump we’re trying to avoid.

**Comment by kof** [comment]
Btw. the overlay can be bigger then the orgiinal component, it can start at the same top position and go down, similar to how browser implement alert boxes, it can be really big. Just set the max height and make it scrollbar.

**Comment by kof** [comment]
By min-height I ment a min-height that is always defined, not just when an error comes, but with my previous suggestion you don't need a min-height.

**Comment by sapegin** [comment]
So it would overlap the code? But I’m also thinking about something like that.

**Comment by kof** [comment]
> So it would overlap the code? But I’m also thinking about something like that.

yes

**Comment by UsulPro** [comment]
Maybe [demo page](https://usulpro.github.io/react-styleguidist/) to play with this feature could help?

to clarify: 
it keeps the code only if an error appears after you focus CodeMirror box and while you're in the box.
if error was in the source code it shows immediately
if you blur CodeMirror box it shows immediately
if you blur CodeMirror box and then returned it still shows error

Since it could be easily enabled/disabled in `PlaygroundRenderer` and `EditorRenderer` maybe it worth to add some keyboard shortcut for it?

about notifiction via border color I was just looking for the most minimalistic way to don't destroy the existing design. of course this maybe not the final decision

**Comment by sapegin** [comment]
I‘m closing this for now. We definitely can and should improve the error handling in the code editor but probably this is not the right direction for Styleguidist. Thank you for your work anyway!

**Pull request closed without merging**
