### PR TITLE
Distinguish active projects from inactive

### PR DESCRIPTION
**Pull request by mccalluc**
This list was really helpful! An active/inactive distinction seems pretty clear... but beyond that which tool is best for the job gets much more subjective.

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks for the PR!

I'm wondering do we really need inactive tools anymore? How did you determine which ones are inactive?

**Comment by mccalluc** [comment]
For the inactive ones, I've added a note at the end of the line saying when the last release was... or actually, the last commit to github: that was easier to get.

Your call: For me, having this exhaustive list was really useful, and made me more confident about my choice in the end.

**Comment by sapegin** [comment]
Yeah, that makes sense!

**Comment by sapegin** [comment]
I'll merge as soon as I figure out why CI isn't working. It's not related to your changes 🤷‍♂

**Pull request merged**
