### PR TITLE
Sections with href rendering fix

### LINKED ISSUE #1141: Sections with href don't render correctly in sidebar
**Current behavior**

When using href in a section the sidebar does not render correctly.

**To reproduce**

Given the following section:
```
{
    name: 'Product (Internal)',
    content: 'config/style-guide/sections/product/introduction.md',
    sections: [
        {
            name: 'Design',
            href: 'https://sites.google.com/spothero.com/product-design/design-systems',
            external: true
        },
        {
            name: 'Web Pattern Library',
            href: 'https://spothero.invisionapp.com/share/CQL70LPMV3D#/screens',
            external: true
        }
    ]
},
```

You get the following output: 

**Expected behavior**

Simply changing to this section code:
```
{
    name: 'Product (Internal)',
    content: 'config/style-guide/sections/product/introduction.md',
    sections: [
        {
            name: 'Design',
            content: 'config/style-guide/sections/styling/colors.md'
        },
        {
            name: 'Web Pattern Library',
            content: 'config/style-guide/sections/styling/responsive.md'
        }
    ]
},
```

You get the following, correct display: 

When I inspect the incorrect code Product heading in the sidebar, i see that it has an `isChild` class applied to it for some reason.

### PR DESCRIPTION
**Pull request by arshadkazmi42**
Added handler for openInNewTab in ComponentList to handle the href tags

Closes #1141

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
Oh. I think I create a branch from master, thats why its giving these many conflicts.

**Comment by sapegin** [comment]
I've changed the branch. I guess you can do it yourself too — *Edit* button in the top right corner of this page.

**Comment by arshadkazmi42** [comment]
@sapegin ok. thanks
I will create a new PR now.

**Comment by arshadkazmi42** [comment]
@sapegin I can't find  `rsg-components` directory in `src` folder in next branch.

**Comment by arshadkazmi42** [comment]
created a new PR here #1161

**Pull request closed without merging**
