### PR TITLE
Playground passes evalInContext to Slot

### LINKED ISSUE #977: Pass evalInContext to Slot
**The problem**
In order to support a proposed "show HTML" slot plugin, the `Slot` component will need access to `evalInContext` which is passed to the `Playground` so that it can use the `CodeEvaluator` proposed in #976.

**Proposed solution**
Update `Playground` to pass `evalInContext` to `Slot`

### PR DESCRIPTION
**Pull request by kidkuro**
Fixes #977

`Playground` passes `evalInContext` to `Slot`

### CODE REVIEW

**Comment by kidkuro** [comment]
I am getting 503 errors attempting to run Cyprus locally to try to reproduce the problem. The error seems unlikely to be related to my change, since this simply passes an extra config option which isn't being used. Not sure how to proceed from here.

**Comment by kidkuro** [comment]
The "Single component preview section changes the render after code change" is failing with a timeout. The code waits for 500ms. I just tried manually executing the scenario by typing into the code editor... and it looks like the lag between type and update could easily exceed that timeout in a real browser environment. Could it be that timeout is too short and is fragile? Again... this doesn't appear to be due to my change.

**Comment by sapegin** [comment]
Yeah, we have some issues with this test: https://github.com/styleguidist/react-styleguidist/issues/895

Restarting the CI usually helps.

**Comment by sapegin** [comment]
Thanks!

(I’ve also increased the timeout in that test — hope it would help, couldn't find a way to avoid the timeout unfortunately.)

**Pull request merged**
