### PR TITLE
clear console on reload

### LINKED ISSUE #519: Run console.clear() when components are reloaded
It's a bit irritating to see an error in your console and not know if it's from the current component that was hot-loaded in or from an older version.

This would be solved by running `console.clear()` once a component has been reloaded (or if multiple components are being reloaded, after they're all reloaded).

### PR DESCRIPTION
**Pull request by xjlim**
fix #519

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks, merged!

**Comment by BruceHubbard** [comment]
What was the logic behind clearing the console?  I recently updated my styleguidist version and I've noticed all of my React warnings are now hidden because the console gets cleared here.

**Comment by sapegin** [comment]
@BruceHubbard I guess it shouldn’t be cleared on hard page reload, only on HMR updates. If it’s not the case, then it’s a bug.

**Comment by BruceHubbard** [comment]
@sapegin I'll open a new issue and see if others are having the same problem.  On a hard page reload in Chrome I end up with zero React warnings when I know I should have some.

**Pull request merged**
