### PR TITLE
Fix/exit isolated button fix

### PR DESCRIPTION
**Pull request by stepancar**
What happens:
When going into the isolation example and trying to go back button have text 'Exit isolated'.

What should happen: Button should have text 'Open isolated'

To reproduce,

go to https://react-styleguidist.js.org/examples/basic/#button

Press "Open isolated" in Playground
In the newly opened page, press "Exit isolated"
Observe you are now on component page, but button in playground still have "Exit isolated text"

This fix update Playground on context change.
Added test

### CODE REVIEW

**Comment by sapegin** [comment]
Thanks for the pull request! I think it’s already fixed in the `ui` branch, I’ll check again.

**Comment by stepancar** [comment]
as I see , it's not fixed https://github.com/styleguidist/react-styleguidist/blob/ui/src/rsg-components/Playground/Playground.js#L36

**Comment by sapegin** [comment]
It’s not the latest code anyway, *I’ll check it again when I finish the new UI*.

**Comment by sapegin** [comment]
I can’t reproduce it in the `ui` branch now (pushed the latest changes).

**Pull request closed without merging**
